services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: nest-oracle
    environment:
      - ORACLE_PWD=nest123
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./docker/oracle/init:/opt/oracle/scripts/startup

volumes:
  oracle-data: