ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER nestdba IDENTIFIED BY "nest123" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER TO nestdba;