CREATE TABLE TB_USER (
    ID          NUMBER DEFAULT SEQ_USER.NEXTVAL NOT NULL,
    NAME        VARCHAR2(100)                   NOT NULL,
    EMAIL       VARCHAR2(150)                   NOT NULL,
    PASSWORD    VARCHAR2(255)                   NOT NULL,
    ROLE        VARCHAR2(20)                    NOT NULL,
    ACTIVE      NUMBER(1)       DEFAULT 1       NOT NULL,
    CREATED_AT  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (ID),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_USER_ROLE CHECK (ROLE IN ('OPERATOR', 'MANAGER', 'LEADER')),
    CONSTRAINT CK_USER_ACTIVE CHECK (ACTIVE IN (0, 1))
);

CREATE TABLE TB_STRATEGIC_GUIDELINE (
    ID          NUMBER DEFAULT SEQ_STRATEGIC_GUIDELINE.NEXTVAL NOT NULL,
    TITLE       VARCHAR2(150)                   NOT NULL,
    CONTENT     VARCHAR2(4000)                  NOT NULL,
    ACTIVE      NUMBER(1)       DEFAULT 1       NOT NULL,
    CREATED_BY  NUMBER                          NOT NULL,
    CREATED_AT  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_STRATEGIC_GUIDELINE PRIMARY KEY (ID),
    CONSTRAINT FK_GUIDELINE_USER FOREIGN KEY (CREATED_BY) REFERENCES TB_USER(ID),
    CONSTRAINT CK_GUIDELINE_ACTIVE CHECK (ACTIVE IN (0, 1))
);

CREATE TABLE TB_IDEA (
    ID          NUMBER DEFAULT SEQ_IDEA.NEXTVAL  NOT NULL,
    TITLE       VARCHAR2(150)                    NOT NULL,
    DESCRIPTION VARCHAR2(4000)                   NOT NULL,
    STATUS      VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL,
    PRIORITY    NUMBER,
    SUBMITTED_BY NUMBER                          NOT NULL,
    REVIEWED_BY  NUMBER,
    REVIEWED_AT  TIMESTAMP,
    CREATED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_IDEA PRIMARY KEY (ID),
    CONSTRAINT FK_IDEA_SUBMITTED_BY FOREIGN KEY (SUBMITTED_BY) REFERENCES TB_USER(ID),
    CONSTRAINT FK_IDEA_REVIEWED_BY  FOREIGN KEY (REVIEWED_BY)  REFERENCES TB_USER(ID),
    CONSTRAINT CK_IDEA_STATUS CHECK (STATUS IN ('PENDING', 'PRIORITIZED', 'APPROVED', 'REJECTED'))
);

CREATE TABLE TB_PROJECT (
    ID                  NUMBER DEFAULT SEQ_PROJECT.NEXTVAL NOT NULL,
    TITLE               VARCHAR2(150)                      NOT NULL,
    DESCRIPTION         VARCHAR2(4000)                     NOT NULL,
    STATUS              VARCHAR2(20)    DEFAULT 'PLANNING' NOT NULL,
    STAGE               VARCHAR2(20)    DEFAULT 'IDEATION' NOT NULL,
    INVESTMENT          NUMBER(15, 2)                      NOT NULL,
    EXPECTED_RETURN     NUMBER(15, 2)                      NOT NULL,
    ACTUAL_RETURN       NUMBER(15, 2),
    PRODUCTIVITY_GAIN   NUMBER(5, 2),
    START_DATE          DATE                               NOT NULL,
    END_DATE            DATE,
    CREATED_BY          NUMBER                             NOT NULL,
    IDEA_ID             NUMBER,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PROJECT PRIMARY KEY (ID),
    CONSTRAINT FK_PROJECT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES TB_USER(ID),
    CONSTRAINT FK_PROJECT_IDEA       FOREIGN KEY (IDEA_ID)     REFERENCES TB_IDEA(ID),
    CONSTRAINT CK_PROJECT_STATUS CHECK (STATUS IN ('PLANNING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT CK_PROJECT_STAGE  CHECK (STAGE  IN ('IDEATION', 'VALIDATION', 'PLANNING', 'EXECUTION', 'MONITORING', 'COMPLETED'))
);